name: Ubuntu build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - run: git describe --tags --dirty --match 'v*'
    - name: Install dependencies
      run: |
          sudo apt install -y re2c mcpp patchutils
    - name: Configure CMake
      run: | 
          cmake -DSOUFFLE_USE_SQLITE=OFF -DSOUFFLE_USE_ZLIB=OFF -DSOUFFLE_FAST_RELEASE=OFF -DSOUFFLE_FAST_DEBUG=OFF -B${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Test
      run: cd ${{github.workspace}}/build && ctest -j4 --output-on-failure
    - name: Move file
      run: mv ${{github.workspace}}/build/logifix "${{github.workspace}}/build/logifix-$(git describe --tags --dirty --match 'v*')-ubuntu-x86_64"
    - uses: actions/upload-artifact@v2
      with:
        name: logifix-ubuntu
        path: ${{github.workspace}}/build/logifix-*
