name: Ubuntu build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - run: git describe --tags --dirty --match 'v*'
    - name: Install dependencies
      run: |
          sudo apt install -y re2c mcpp patchutils
    - name: Configure CMake
      run: | 
          cmake -DSOUFFLE_USE_SQLITE=OFF -DSOUFFLE_USE_ZLIB=OFF -DSOUFFLE_FAST_RELEASE=OFF -DSOUFFLE_FAST_DEBUG=OFF -B${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Test
      run: cd ${{github.workspace}}/build && ctest -j4 --output-on-failure
    - uses: actions/upload-artifact@v2
      with:
        name: logifix-ubuntu
        path: ${{github.workspace}}/build/logifix

  compile-spotbugs:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download logifix
      uses: actions/download-artifact@v2
      with:
        name: logifix-ubuntu
    - run: git clone --depth 1 https://github.com/spotbugs/spotbugs.git
    - run: cd spotbugs && ./gradlew build -x test
    - run: chmod +x logifix
    - run: ./logifix --in-place --accept-all spotbugs/src/main/java/
    - run: cd spotbugs && ./gradlew build -x test

  check-for-compile-errors:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download logifix
      uses: actions/download-artifact@v2
      with:
        name: logifix-ubuntu
    - run: git clone --depth 1 https://github.com/INRIA/spoon.git
    - run: cd spoon && mvn compile
    - run: chmod +x logifix
    - run: ./logifix --in-place --accept-all spoon/src/main
    - run: cd spoon && mvn compile

  compile-bytecodeviewer:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download logifix
      uses: actions/download-artifact@v2
      with:
        name: logifix-ubuntu
    - run: git clone --depth 1 https://github.com/Konloch/bytecode-viewer.git
    - run: cd bytecode-viewer && mvn compile
    - run: chmod +x logifix
    - run: ./logifix --in-place --accept-all bytecode-viewer/
    - run: cd bytecode-viewer && mvn compile

  compile-primefaces:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download logifix
      uses: actions/download-artifact@v2
      with:
        name: logifix-ubuntu
    - run: git clone --depth 1 https://github.com/primefaces/primefaces.git
    - run: cd primefaces && mvn compile -Dcheckstyle.skip
    - run: chmod +x logifix
    - run: ./logifix --in-place --accept-all primefaces/
    - run: cd primefaces && mvn compile -Dcheckstyle.skip

  compile-initializr:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download logifix
      uses: actions/download-artifact@v2
      with:
        name: logifix-ubuntu
    - run: git clone --depth 1 https://github.com/spring-io/initializr.git
    - run: cd initializr && mvn compile
    - run: chmod +x logifix
    - run: ./logifix --in-place --accept-all initializr/
    - run: cd initializr && mvn spring-javaformat:apply
    - run: cd initializr && mvn compile

  compile-pitest:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download logifix
      uses: actions/download-artifact@v2
      with:
        name: logifix-ubuntu
    - run: git clone --depth 1 https://github.com/hcoles/pitest.git
    - run: cd pitest && mvn compile
    - run: chmod +x logifix
    - run: ./logifix --in-place --accept-all pitest/
    - run: cd pitest && mvn compile

  compile-caffeine:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download logifix
      uses: actions/download-artifact@v2
      with:
        name: logifix-ubuntu
    - run: git clone --depth 1 https://github.com/ben-manes/caffeine.git
    - run: cd caffeine && ./gradlew build -x test
    - run: chmod +x logifix
    - run: ./logifix --in-place --accept-all caffeine/
    - run: cd caffeine && ./gradlew build -x test

  compile-testng:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download logifix
      uses: actions/download-artifact@v2
      with:
        name: logifix-ubuntu
    - run: git clone --depth 1 https://github.com/cbeust/testng.git
    - run: cd testng && ./gradlew build -x test
    - run: chmod +x logifix
    - run: ./logifix --in-place --accept-all testng/
    - run: cd testng && ./gradlew autostyleApply
    - run: cd testng && ./gradlew build -x test
